"""Independent feature modules for the Lost Castle 2 toolbox."""

from .combat_aggregator import (
    CombatAggregator,
    CombatEventError,
    CombatSnapshot,
    ScenarioInfo,
    ScenarioRegistry,
    SequenceError,
    SessionMismatchError,
    SourceInfo,
    SourceRegistry,
)
from .app_shell import (
    MacroRow,
    ToolboxShell,
    combat_state_label,
    format_location_label,
    format_metric,
    format_room_area,
    format_stage_location,
    macro_rows,
    metric_font_size,
    seed_demo_combat,
)
from .combat_transport import (
    CombatBridgeClient,
    CombatDrainReport,
    CombatEventPump,
    CombatEventValidator,
    CombatInbox,
    CombatLineDecoder,
    CombatProtocolError,
    CombatSchemaError,
    TransportNotice,
)
from .macro_engine import MacroController, MacroState
from .macro_model import MacroProfile, MacroProfileError, parse_macro_profile
from .mod_manager import (
    ModCatalog,
    ModDescriptor,
    ModIntegrityError,
    ModManager,
    ModManagerError,
    ModSourceRequired,
    ModStatus,
)

__all__ = [
    "CombatAggregator",
    "CombatEventError",
    "CombatSnapshot",
    "CombatBridgeClient",
    "CombatDrainReport",
    "CombatEventPump",
    "CombatEventValidator",
    "CombatInbox",
    "CombatLineDecoder",
    "CombatProtocolError",
    "CombatSchemaError",
    "MacroRow",
    "MacroController",
    "MacroProfile",
    "MacroProfileError",
    "MacroState",
    "ModCatalog",
    "ModDescriptor",
    "ModIntegrityError",
    "ModManager",
    "ModManagerError",
    "ModSourceRequired",
    "ModStatus",
    "ScenarioInfo",
    "ScenarioRegistry",
    "SequenceError",
    "SessionMismatchError",
    "SourceInfo",
    "SourceRegistry",
    "ToolboxShell",
    "TransportNotice",
    "combat_state_label",
    "format_location_label",
    "format_metric",
    "format_room_area",
    "format_stage_location",
    "macro_rows",
    "metric_font_size",
    "seed_demo_combat",
    "parse_macro_profile",
]
